In [1]:
!pip install spepy

In [ ]:
import spepy

sepy.speak

Thank you for downloading this library. I'd like to thanks Aman Raj, my Quora friend for the idea.
NOTE, This library is for windows only.


In [ ]:
import datetime

datetime.datetime.now()

SyntaxError: invalid syntax (3359921439.py, line 3)

In [12]:
!pip install pyjokes

In [24]:
import pyjokes

print(pyjokes.get_joke())

You don't have to know how the computer works, just how to work the computer.


In [31]:
import pyjokes

user_input=input("enter your mood:")

if "joke" in user_input:
    
    spepy.speak(pyjokes.get_joke())
    
elif "exit" in user_input:
    spepy.speak("goodbye")     

In [33]:
!pip install moment

  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)

   ---------------------------------------- 0/8 [pytz]
   ---------------------------------------- 0/8 [pytz]
   ---------------------------------------- 0/8 [pytz]
   ---------------------------------------- 0/8 [pytz]
   ----- ---------------------------------- 1/8 [tzdata]
   ----- ---------------------------------- 1/8 [tzdata]
   ----- ---------------------------------- 1/8 [tzdata]
   ----- ---------------------------------- 1/8 [tzdata]
   ---------- ----------------------------- 2/8 [regex]
   ---------- ----------------------------- 2/8 [regex]
   --------------- ------------------------ 3/8 [tzlocal]
   -------------------- ------------------- 4/8 [arrow]
   -------------------- ------------------- 4/8 [arrow]
   ---------------------

In [27]:
import moment

date=moment.date("11-27-2025")

moment.utcnow().timezone("Asia/Karachi").date

datetime.datetime(2025, 11, 29, 22, 39, 44, 230237, tzinfo=zoneinfo.ZoneInfo(key='Asia/Karachi'))

In [25]:
import spepy
import pyjokes

spepy.speak(pyjokes.get_joke())

In [3]:
!pip install numpy

  Using cached numpy-2.3.5-cp313-cp313-win_amd64.whl.metadata (60 kB)
Using cached numpy-2.3.5-cp313-cp313-win_amd64.whl (12.8 MB)


In [ ]:
import numpy as np

x=np.array([9,8,4])
y=np.array([1,5,7])
print(x*y)
print(x-y)
print(x+y)
print(x%y)

[ 9 40 28]
[ 8  3 -3]
[10 13 11]
[0 3 4]


In [4]:
x=np.array([9,8,4])
y=np.array([1,5,7])

import numpy as np
print(x.ndim)
x=np.append(x,5)
y=np.append(y,3)

print(x)
print(y)

1
[9 8 4 5]
[1 5 7 3]


In [12]:
import numpy as np

x=np.array([[9,8],[1,3]])
y=np.array([[2,9],[10,7]])

c=x-y
print(c)

[[ 7 -1]
 [-9 -4]]


In [2]:
import numpy as np

numbers=np.ones(4)
matrix=np.ones((10,20))

age=np.arange(20)

diag=np.eye(4)
zoop=np.eye(7,8)
points=np.linspace(1,100,10)
print(points)
print(zoop)
print(diag)


[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
import numpy as np

heights=np.array([14,56,78,99,78,56,65,32])

print(np.pow(heights,1.2))
print(np.multiply(heights,7))
print(np.mod(heights,5))

[ 23.73305484 125.26381445 186.42902283 248.17740177 186.42902283
 125.26381445 149.79455529  64.        ]
[ 98 392 546 693 546 392 455 224]
[4 1 3 4 3 1 0 2]


In [1]:
import numpy as np

randomAxis = np.random.rand(4) * 50

ages=np.random.randint(0,80,(5,10))

